src/calc.ts
tsconfig.json

now u can:
40 000 + 10 555
and:
3,1415+2.2
and
1/$

Calc improvements

---

src/api.ts
src/kino.ts
src/main.ts
src/matoshi.ts

Dev environment support 

---

.gitignore
guildCommands.json
src/database.ts
src/main.ts
src/stockPresets.ts
src/stocks.ts

Add stock fees policy for each stock

---

src/main.ts
src/utilities.ts

Convert all audio sources to readable stream

---

guildCommands.json
src/main.ts
src/matoshi.ts

added fees for services

---

guildCommands.json
src/main.ts
src/stocks.ts

Add stocks total

---

src/main.ts
src/polls.ts

minor fixes

---

package-lock.json
package.json
src/main.ts

feat: logging with timestamp

---

src/kino.ts
src/sheets.ts

feat: write film name to sheets when watching

---

.gitignore
src/main.ts

reminders now accept multiple units `2d 5h`
reminders now show time remaining

Improved reminders

---

globalCommands.json
src/main.ts

feat: reminder removing

---

src/sheets.ts

fix 2 days offset sheets

---

src/kino.ts
src/matoshi.ts

don't tax if no tax

---

src/assignments.ts

assignment matoshi reward

---

guildCommands.json
src/main.ts
src/matoshi.ts
src/policy.ts
src/user.ts

rank is no longer broken

---

src/assignments.ts
src/matoshi.ts
src/stockPresets.ts
src/stocks.ts
src/user.ts

minor fixes, including but not limited to #116

---

src/main.ts
src/matoshi.ts

Fix pay/acceptPayment transaction fee

---

src/kino.ts
src/main.ts

closes https://github.com/Mylapqn/jacekkocek/issues/119

fix kino event time

---

src/matoshi.ts

silent tax report

---

src/assignments.ts
src/user.ts

assignments improvements

---

src/kino/kino.ts
src/polls.ts

fix zběsilá kino pingala
